<script type="module">
  import PageTransition from "../lib/PageTransition.svelte";
  import Container from "../lib/Container.svelte";
  import Gallery from "../lib/Gallery.svelte";
</script>

<PageTransition>
  <Container variant="fullWidth">
    <Gallery
      images={[
        {
          src: "/gallery/nick.jpg",
          srcPreview: "/gallery/nick-sml.jpg",
          alt: "Nick Care conducting",
          width: 1258,
          height: 1533,
        },
        {
          src: "/gallery/amc-db-doin-time.jpg",
          srcPreview: "/gallery/amc-db-doin-time-sml.jpg",
          alt: "Doin' Time recording session",
          width: 2942,
          height: 1614,
        },
        {
          src: "/gallery/btl-recording.jpg",
          srcPreview: "/gallery/btl-recording-sml.jpg",
          alt: "Beyond the Limit recording session with Salena Jones",
          width: 2337,
          height: 1581,
        },
        {
          src: "/gallery/tjb-rfh.jpg",
          srcPreview: "/gallery/tjb-rfh-sml.jpg",
          alt: "Turnfurlong Jazz Band at the Royal Festival Hall",
          width: 2331,
          height: 1569,
        },
        {
          src: "/gallery/bernwode-festival-orch-2003.jpg",
          srcPreview: "/gallery/bernwode-festival-orch-2003-sml.jpg",
          alt: "Bernwode Festival Orchestra 2003",
          width: 1722,
          height: 1620,
        },
        {
          src: "/gallery/jwb-winslow.jpg",
          srcPreview: "/gallery/jwb-winslow-sml.jpg",
          alt: "Aylesbury Music Centre Junior Wind Band (Winslow)",
          width: 2560,
          height: 1920,
        },
        {
          src: "/gallery/brass-tacks.jpg",
          srcPreview: "/gallery/brass-tacks-sml.jpg",
          alt: "Brass Tacks",
          width: 4295,
          height: 3094,
        },
        {
          src: "/gallery/jbb.jpg",
          srcPreview: "/gallery/jbb-sml.jpg",
          alt: "JBB??",
          width: 2272,
          height: 1704,
        },
        {
          src: "/gallery/benslow-aug-10.jpg",
          srcPreview: "/gallery/benslow-aug-10-sml.jpg",
          alt: "Benslow",
          width: 4000,
          height: 3000,
        },
        {
          src: "/gallery/ahs-jazz-babes.jpg",
          srcPreview: "/gallery/ahs-jazz-babes-sml.jpg",
          alt: "Aylesbury High School Jazz Babes",
          width: 2272,
          height: 1704,
        },
        {
          src: "/gallery/guernsey-2003-iwb.jpg",
          srcPreview: "/gallery/guernsey-2003-iwb-sml.jpg",
          alt: "On tour in Guernsey with Aylesbury Music Centre Intermediate Wind Band, 2003",
          width: 2354,
          height: 1586,
        },
        {
          src: "/gallery/amc-db-telegraph-1989.jpg",
          srcPreview: "/gallery/amc-db-telegraph-1989-sml.jpg",
          alt: "Daily Telegraph snippet about Aylesbury Music Centre Dance Band, 1989",
          width: 6596,
          height: 2240,
        },
        {
          src: "/gallery/farnaby-brass.jpg",
          srcPreview: "/gallery/farnaby-brass-sml.jpg",
          alt: "Farnaby Brass",
          width: 3306,
          height: 4676,
        },
        {
          src: "/gallery/amc-db-skip-mid-90s.jpg",
          srcPreview: "/gallery/amc-db-skip-mid-90s-sml.jpg",
          alt: "Aylesbury Music Centre Dance Band in a skip, mid-90s",
          width: 3805,
          height: 2743,
        },
        {
          src: "/gallery/brass-tacks-1980s.jpg",
          srcPreview: "/gallery/brass-tacks-1980s-sml.jpg",
          alt: "Brass Tacks in the 1980s",
          width: 2485,
          height: 3320,
        },
        {
          src: "/gallery/2001-monster-brass-crispian-steele-perkins-conducting.jpg",
          srcPreview: "/gallery/2001-monster-brass-crispian-steele-perkins-conducting-sml.jpg",
          alt: "Monster Brass with Crispian Steele-Perkins conducting, 2001",
          width: 1653,
          height: 2440,
        },
        {
          src: "/gallery/rah-jules-buckley-2019.jpg",
          srcPreview: "/gallery/rah-jules-buckley-2019-sml.jpg",
          alt: "At the Royal Albert Hall with Jules Buckley after a rehearsal, 2019",
          width: 4032,
          height: 3024,
        },
        {
          src: "/gallery/with-trumpet.jpg",
          srcPreview: "/gallery/with-trumpet-sml.jpg",
          alt: "Nick reclining with a trumpet",
          width: 3169,
          height: 3360,
        },
        {
          src: "/gallery/amc-dance-band-at-ags.jpg",
          srcPreview: "/gallery/amc-dance-band-at-ags-sml.jpg",
          alt: "Aylesbury Music Centre Dance Band playing at Aylesbury Grammar School, mid-90s",
          width: 3507,
          height: 2408,
        },
        {
          src: "/gallery/blue-peter-1992.jpg",
          srcPreview: "/gallery/blue-peter-1992-sml.jpg",
          alt: "Aylesbury Music Centre Dance Band on Blue Peter, 1992",
          width: 3232,
          height: 1948,
        },
        {
          src: "/gallery/john-dankworth-rehearsal.jpg",
          srcPreview: "/gallery/john-dankworth-rehearsal-sml.jpg",
          alt: "In rehearsal with John Dankworth",
          width: 2560,
          height: 1920,
        },
        {
          src: "/gallery/nick-laughing-tring.jpg",
          srcPreview: "/gallery/nick-laughing-tring-sml.jpg",
          alt: "Nick laughing during a concert at Tring",
          width: 3088,
          height: 3088,
        },
        {
          src: "/gallery/with-kenny-wheeler-norma-winstone.jpg",
          srcPreview: "/gallery/with-kenny-wheeler-norma-winstone-sml.jpg",
          alt: "With Kenny Wheeler and Norma Winstone and Aylesbury Music Centre Dance Band, early 2000s",
          width: 2560,
          height: 1920,
        },
        {
          src: "/gallery/nick-and-pic-gift.jpg",
          srcPreview: "/gallery/nick-and-pic-gift-sml.jpg",
          alt: "Nick enjoying some music",
          width: 650,
          height: 745,
        },
        {
          src: "/gallery/berko-2018-back.jpg",
          srcPreview: "/gallery/berko-2018-back-sml.jpg",
          alt: "At a concert in Berhampstead, 2018",
          width: 3088,
          height: 3088,
        },
        {
          src: "/gallery/with-mike-lovatt-2018.jpg",
          srcPreview: "/gallery/with-mike-lovatt-2018-sml.jpg",
          alt: "With Mike Lovatt, 2018",
          width: 3088,
          height: 3088,
        },
        {
          src: "/gallery/nationaal-bevrijdingsmuseum-jul-2013.jpg",
          srcPreview: "/gallery/nationaal-bevrijdingsmuseum-jul-2013-sml.jpg",
          alt: "At the Nationaal Bevrijdingsmuseum in the Netherlands, July 2013",
          width: 1024,
          height: 680,
        },
        {
          src: "/gallery/turnfurlong-jazz-band.jpg",
          srcPreview: "/gallery/turnfurlong-jazz-band-sml.jpg",
          alt: "Turnfurlong Jazz Band",
          width: 1501,
          height: 1445,
        },
        {
          src: "/gallery/amc-big-band-recording-bbc-studios.jpg",
          srcPreview: "/gallery/amc-big-band-recording-bbc-studios-sml.jpg",
          alt: "Aylesbury Music Centre Dance Band recording at BBC studios",
          width: 1441,
          height: 1109,
        },
        {
          src: "/gallery/turnfurlong-jazz-band-2003.jpg",
          srcPreview: "/gallery/turnfurlong-jazz-band-2003-sml.jpg",
          alt: "Turnfurlong Jazz Band, 2003",
          width: 1760,
          height: 1704,
        },
        {
          src: "/gallery/django-bates-tv-prog-2005.jpg",
          srcPreview: "/gallery/django-bates-tv-prog-2005-sml.jpg",
          alt: "On TV with Django Bates, Iain Ballamy and Martin France, 2005",
          width: 2272,
          height: 1704,
        },
      ]}
    />
  </Container>
</PageTransition>
